### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by gsteinbu** [snakemake-workflows/ngs-test-data#6]
Would you care adding one?

**Comment by dlaehnemann** [comment]
Sure, just got pointed to this. Sorry we overlooked this one previously.

I just double-checked which resources we are using in this workflow, which are:

* ArrayExpress, which seems to be part of BioStudies, which [according to its FAQ](https://www.ebi.ac.uk/biostudies/help#) seems to simply use the [`EBI Terms of Use`](https://www.ebi.ac.uk/about/terms-of-use/)
* Biomart and FTP downloads from Ensembl, which do not signify any licensing necessary, so according to [this EMBL-EBI licensing page from the ebi.ac.uk website footer](https://www.ebi.ac.uk/licencing), I would assume that the [`EBI Terms of Use`](https://www.ebi.ac.uk/about/terms-of-use/) also apply to them

So I'll just add some attribution links first, and then add an MIT licencse.

**Comment by dlaehnemann** [comment]
Should be closed by #8. Feel free to re-open, if any respective issues remain. Or open a new issue for other things.

**Comment by gsteinbu** [comment]
Great, many thanks!
